name: Check Old Snapshots
on:
  schedule: # execute every day 8:00
  - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write
jobs:
  clean:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    if: github.repository == 'MrXiaoM/Overflow'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Clean Artifacts
        run: ./gradlew deleteOutdatedArtifacts -DjustTasks
        env:
          ORG_GRADLE_PROJECT_MAVEN_AUTHORIZATION: ${{ secrets.OSSRH_AUTHORIZATION }}
